# Generated by Django 3.2.9 on 2021-12-14 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('timestamp', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 14, 17, 7, 51, 149242))),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emailsafe_api.emaillist')),
            ],
        ),
    ]
