# Generated by Django 3.2.9 on 2021-12-21 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('envelope', models.JSONField(blank=True, default=dict, null=True)),
                ('headers', models.JSONField(blank=True, default=dict, null=True)),
                ('plain', models.JSONField(blank=True, default=dict, null=True)),
                ('html', models.JSONField(blank=True, default=dict, null=True)),
                ('reply_plain', models.JSONField(blank=True, default=dict, null=True)),
                ('attachments', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_report', models.JSONField(blank=True, default=dict, null=True)),
                ('sender_email', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('sender_domain', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('domain_report', models.JSONField(blank=True, default=dict, null=True)),
                ('is_phish_url', models.BooleanField(default=None, null=True)),
                ('parent_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='emailsafe_api.emailitem')),
            ],
        ),
    ]
