# Generated by Django 3.2.9 on 2021-12-16 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 37, 28, 328910, tzinfo=utc))),
                ('envelope', models.JSONField(default=dict, null=True)),
                ('headers', models.JSONField(default=dict, null=True)),
                ('plain', models.JSONField(default=dict, null=True)),
                ('html', models.JSONField(default=dict, null=True)),
                ('reply_plain', models.JSONField(default=dict, null=True)),
                ('attachments', models.JSONField(default=dict, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
