# Generated by Django 3.2.9 on 2021-12-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='parent_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='emailsafe_api.emailitem'),
        ),
    ]
