# Generated by Django 3.2.9 on 2021-12-14 22:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailsafe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 22, 25, 13, 20913, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='EmailList',
        ),
    ]
