# Generated by Django 3.2.9 on 2021-12-20 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 17, 50, 24, 420110, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_report', models.JSONField(blank=True, default=dict, null=True)),
                ('parent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='emailsafe_api.emailitem')),
            ],
        ),
    ]
