# Generated by Django 3.2.9 on 2021-12-14 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0002_auto_20211214_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 22, 25, 18, 348423, tzinfo=utc)),
        ),
    ]
