# Generated by Django 3.2.9 on 2021-12-20 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0002_auto_20211220_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 17, 53, 13, 227930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='parent_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='emailsafe_api.emailitem'),
        ),
    ]
