# Generated by Django 3.2.9 on 2021-12-16 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0005_alter_emailitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailitem',
            name='sender',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 3, 10, 30, 392505, tzinfo=utc)),
        ),
    ]
