# Generated by Django 3.2.9 on 2021-12-16 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0006_auto_20211216_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='sender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 3, 11, 20, 477996, tzinfo=utc)),
        ),
    ]
