# Generated by Django 3.2.9 on 2021-12-20 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0007_alter_emailitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 18, 10, 15, 458070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='parent_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='emailsafe_api.emailitem'),
        ),
    ]
