# Generated by Django 3.2.9 on 2021-12-16 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0007_auto_20211216_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 3, 12, 4, 774158, tzinfo=utc)),
        ),
    ]
