# Generated by Django 3.2.9 on 2021-12-20 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0008_auto_20211220_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment_missing',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 18, 20, 46, 239838, tzinfo=utc)),
        ),
    ]
