# Generated by Django 3.2.9 on 2021-12-16 04:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0010_alter_emailitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 4, 27, 8, 775126, tzinfo=utc)),
        ),
    ]
