# Generated by Django 3.2.9 on 2021-12-20 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0011_auto_20211220_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 19, 29, 25, 878358, tzinfo=utc)),
        ),
    ]
