# Generated by Django 3.2.9 on 2021-12-20 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0018_alter_emailitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='domain_report',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 21, 30, 57, 69736, tzinfo=utc)),
        ),
    ]
