# Generated by Django 3.2.9 on 2021-12-21 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0019_auto_20211220_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_phish_url',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 0, 18, 52, 235557, tzinfo=utc)),
        ),
    ]
