# Generated by Django 3.2.9 on 2021-12-21 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0021_auto_20211221_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 0, 21, 43, 315050, tzinfo=utc)),
        ),
    ]
