# Generated by Django 3.2.9 on 2021-12-21 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailsafe_api', '0025_alter_emailitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
